apiVersion: v1
kind: Pod
metadata:
  name: waste-dbcreator-pod
  labels:
    app: waste-dbcreator
    apptype: waste-coreapp
spec:
  initContainers:
  - name: wait-for-wastelogserver
    image: curlimages/curl:latest
    command: ["/bin/sh","-c"]
    args: ["while [ $(curl -sw '%{http_code}' http://waste-logserver-cluster-ip/readiness -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the WasteLogServer...'; done"]
  containers:
  - name: waste-dbcreator
    image: devafatek/wastedbcreator:1.0
    imagePullPolicy: "Always"
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: waste-psqldb-config
  restartPolicy: Never
