apiVersion: apps/v1
kind: Deployment
metadata:
  name: waste-adminui-deployment
  namespace: waste-system
  labels:
    app: waste-adminui
    apptype: waste-coreapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waste-adminui
  template:
    metadata:
      labels:
        app: waste-adminui
    spec:
      initContainers:
      - name: wait-for-wastelogserver
        image: curlimages/curl:latest
        command: ["/bin/sh","-c"]
        args: ["while [ $(curl -sw '%{http_code}' http://waste-logserver-cluster-ip/readiness -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the WasteLogServer...'; done"]
      - name: wait-for-wasteadminapi
        image: curlimages/curl:latest
        command: ["/bin/sh","-c"]
        args: ["while [ $(curl -sw '%{http_code}' http://waste-adminapi-cluster-ip/readiness -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the WasteAdminApi...'; done"]
      containers:
      - name: waste-adminui
        image: devafatek/wasteadminui
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
