apiVersion: v1
kind: PersistentVolume
metadata:
  name: waste-db-pv-volume
  namespace: waste-system
  labels:
    app: waste-db
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-022d21b44858dcf4e
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waste-db-pv-claim
  namespace: waste-system
  labels:
    app: waste-db
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: waste-db-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
