apiVersion: v1
kind: Pod
metadata:
  name: waste-dbcreator-pod
  namespace: waste-system
  labels:
    app: waste-dbcreator
spec:
  initContainers:
  - name: wait-for-wastestoreapi
    image: curlimages/curl:latest
    command: ["/bin/sh","-c"]
    args: ["while [ $(curl -sw '%{http_code}' http://waste-storeapi-cluster-ip/readiness -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the WasteStoreApi...'; done"]
  containers:
  - name: waste-dbcreator
    image: devafatek/wastedbcreator
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: waste-psqldb-config
  restartPolicy: Never
