apiVersion: v1
kind: Pod
metadata:
  name: waste-systemupdater-pod
  namespace: waste-system
  labels:
    app: waste-systemupdater
    apptype: waste-coreapp
spec:
  initContainers:
  - name: wait-for-wastestoreapi
    image: curlimages/curl:latest
    command: ["/bin/sh","-c"]
    args: ["while [ $(curl -sw '%{http_code}' http://waste-storeapi-cluster-ip/readiness -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the WasteStoreApi...'; done"]
  containers:
  - name: waste-systemupdater
    image: devafatek/wastesystemupdater:1.0
    imagePullPolicy: "Always"
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: waste-psqldb-config
  restartPolicy: Never
