apiVersion: v1
kind: PersistentVolume
metadata:
  name: waste-readerdb-pv-volume
  namespace: waste-system
  labels:
    app: waste-readerdb
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0d78e8e8265bf189d
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waste-readerdb-pv-claim
  namespace: waste-system
  labels:
    app: waste-readerdb
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: waste-readerdb-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
