apiVersion: apps/v1
kind: Deployment
metadata:
  name: waste-logserver-deployment
  namespace: waste-system
  labels:
    app: waste-logserver
    apptype: waste-coreapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waste-logserver
  template:
    metadata:
      labels:
        app: waste-logserver
    spec:
      containers:
      - name: waste-logserver
        image: devafatek/wastelogserver:1.0
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
