apiVersion: v1
kind: PersistentVolume
metadata:
  name: waste-sumdb-pv-volume
  namespace: waste-system
  labels:
    app: waste-sumdb
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0de281684d201d066
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waste-sumdb-pv-claim
  namespace: waste-system
  labels:
    app: waste-sumdb
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: waste-sumdb-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
