apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: waste-storage
  namespace: waste-system
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4 
reclaimPolicy: Retain


