apiVersion: v1
kind: PersistentVolume
metadata:
  name: waste-staticdb-pv-volume
  namespace: waste-system
  labels:
    app: waste-staticdb
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-002a5b9ecba17536b
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waste-staticdb-pv-claim
  namespace: waste-system
  labels:
    app: waste-staticdb
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: waste-staticdb-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
