apiVersion: v1
kind: PersistentVolume
metadata:
  name: waste-bulkdb-pv-volume
  namespace: waste-system
  labels:
    app: waste-bulkdb
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-09b447c22d6784bd3
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waste-bulkdb-pv-claim
  namespace: waste-system
  labels:
    app: waste-bulkdb
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: waste-bulkdb-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
