apiVersion: v1
kind: Service
metadata:
  name: waste-gpsreader-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: waste-gpsreader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
