apiVersion: v1
kind: Service
metadata:
  name: waste-reportapi-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: waste-reportapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
