apiVersion: v1
kind: Service
metadata:
  name: waste-listener-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: waste-listener
  ports:
    - name: hhtplistener
      port: 80
      targetPort: 80
      nodePort: 30082
    - name: tcplistener
      port: 20000
      targetPort: 20000
      nodePort: 30200
