apiVersion: apps/v1
kind: Deployment
metadata:
  name: waste-psqldb-deployment
  labels:
    app: waste-psqldb
    apptype: waste-dbapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waste-psqldb
  template:
    metadata:
      labels:
        app: waste-psqldb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eu-central-1a
      containers:
        - name: waste-psqldb
          image: postgres:13.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          args: ["-c", "shared_buffers=256MB", "-c", "max_connections=400"]
          envFrom:
            - configMapRef:
                name: waste-psqldb-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: waste-psqldb-vm
              subPath: psqldb
      volumes:
        - name: waste-psqldb-vm
          persistentVolumeClaim:
            claimName: waste-psqldb-pv-claim
