apiVersion: apps/v1
kind: Deployment
metadata:
  name: waste-rfreader-deployment
  labels:
    app: waste-rfreader
    apptype: waste-coreapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: waste-rfreader
  template:
    metadata:
      labels:
        app: waste-rfreader
    spec:
      initContainers:
      - name: wait-for-wastelogserver
        image: curlimages/curl:latest
        command: ["/bin/sh","-c"]
        args: ["while [ $(curl -sw '%{http_code}' http://waste-logserver-cluster-ip/readiness -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the WasteLogServer...'; done"]
      - name: wait-for-wastestoreapi
        image: curlimages/curl:latest
        command: ["/bin/sh","-c"]
        args: ["while [ $(curl -sw '%{http_code}' http://waste-storeapi-cluster-ip/readiness -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the WasteStoreApi...'; done"]
      - name: wait-for-wasteenhcapi
        image: curlimages/curl:latest
        command: ["/bin/sh","-c"]
        args: ["while [ $(curl -sw '%{http_code}' http://waste-enhcapi-cluster-ip/readiness -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the WasteEnhcApi...'; done"]
      containers:
      - name: waste-rfreader
        image: devafatek/wasterfreader:1.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
