apiVersion: v1
kind: PersistentVolume
metadata:
  name: waste-sumdb-pv-volume
  labels:
    app: waste-sumdb
spec:
  storageClassName: gp2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0f12651900609eb50
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waste-sumdb-pv-claim
  labels:
    app: waste-sumdb
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: waste-sumdb-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
