apiVersion: v1
kind: PersistentVolume
metadata:
  name: waste-configdb-pv-volume
  labels:
    app: waste-configdb
spec:
  storageClassName: gp2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-06d3b1509d88b7d03
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waste-configdb-pv-claim
  labels:
    app: waste-configdb
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: waste-configdb-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
