apiVersion: v1
kind: PersistentVolume
metadata:
  name: waste-readerdb-pv-volume
  labels:
    app: waste-readerdb
spec:
  storageClassName: gp2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-01aa3b2f605233b25
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waste-readerdb-pv-claim
  labels:
    app: waste-readerdb
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: waste-readerdb-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
