apiVersion: v1
kind: PersistentVolume
metadata:
  name: waste-staticdb-pv-volume
  labels:
    app: waste-staticdb
spec:
  storageClassName: gp2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0d37d4de473c6c94b
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waste-staticdb-pv-claim
  labels:
    app: waste-staticdb
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: waste-staticdb-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
