apiVersion: v1
kind: PersistentVolume
metadata:
  name: waste-psqldb-pv-volume
  labels:
    app: waste-psqldb
spec:
  storageClassName: gp2
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0d266f645346b888b
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waste-psqldb-pv-claim
  labels:
    app: waste-psqldb
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: waste-psqldb-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
