apiVersion: v1
kind: Service
metadata:
  name: waste-redis-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: waste-redis
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip