apiVersion: v1
kind: Service
metadata:
  name: waste-redis-master-cluster-ip
spec:
  type: ClusterIP
  selector:
    master: waste-redis-master
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip